# Generated by Django 5.2 on 2025-04-24 12:25

from django.db import migrations


# This Django migration removes the travel_date field from the Bus model in the bookings app.
class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bus_travel_date'),
    ]

   # ❌ Remove the 'travel_date' field from the Bus model
    operations = [
        migrations.RemoveField(
            model_name='bus',  # The model we're updating
            name='travel_date', # The field we're removing
        ),
    ]
